
name: Hello Vamsi

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'
  push:
    branches:
      - main    
      
concurrency:
  group: ci-${{ github.workflow }}
  cancel-in-progress: false
jobs:
  manual:
    runs-on: self-hosted
    steps:
      - name: Greetings
        run: echo "manual testing"
      - name: sleep
        run: sleep 30
        
      - name: Greetings
        run: echo "automation testing"
