
name: hello vamsi

on:
  push:
    branches: [main]

jobs:
  demo:
    runs-on: self-hosted 

    steps:
      - name: greetings
        run: echo "hello, vamsi"
      - name: access repo variable
        run: echo ${{ vars.USER_NAME }}
      - name: access repo secrets
        run: echo ${{ secrets.PASSWORD }}
