name: built in variables
on:
  push:
    branches: [main]
  workflow_dispatch: 
jobs:
  job1:
    runs-on: self-hosted
    steps:
     - name: Github
       run: |
        echo "GITHUB_REF - $GITHUB_REF - ${{ github.ref }}"
        echo "GITHUB_WORKFLOW - $GITHUB_WORKFLOW - ${{ github.workflow }}"
        echo "GITHUB_RUN_ID - $GITHUB_RUN_ID - ${{ github.run_id }}"
        echo "GITHUB_RUN_NUMBER - $GITHUB_RUN_NUMBER - ${{ github.run_number }}"
        echo "GITHUB_RUN_ATTEMPT - $GITHUB_RUN_ATTEMPT - ${{ github.run_attempt }}"
        echo "GITHUB_REPOSITORY_OWNER - $GITHUB_REPOSITORY_OWNER	- ${{ github.repository_owner }}"
        echo "GITHUB_REPOSITORY_OWNER_ID - $GITHUB_REPOSITORY_OWNER_ID - ${{ github.repository_owner_id }}"
        echo "GITHUB_RUN_ATTEMPT - $GITHUB_RUN_ATTEMPT - ${{ github.run_attempt }}"
        echo "GITHUB_SERVER_URL - $GITHUB_SERVER_URL - ${{ github.server_url }}"
        echo "GITHUB_SHA - $GITHUB_SHA - ${{ github.sha }}"

  job2:
    runs-on: self-hosted
    steps:
      - name: runners
        run: |
          echo "RUNNER_ARCH - $RUNNER_ARCH - ${{ runner.arch }}"
          echo "RUNNER_DEBUG - $RUNNER_DEBUG - ${{ runner.debug }}"
          echo "RUNNER_ENVIRONMENT - $RUNNER_ENVIRONMENT - ${{ runner.environment }}"
          echo "RUNNER_NAME - $RUNNER_NAME - ${{ runner.name }}"
          echo "RUNNER_OS - $RUNNER_OS - ${{ runner.os }}"
          echo "RUNNER_TEMP - $RUNNER_TEMP - ${{ runner.temp }}"
        

       
